import os

# ---------- ENVIRONMENT VARIABLES ----------
SOURCE = os.environ.get("SOURCE")
BATCH_SIZE = os.environ.get("BATCH_SIZE")
RAW_DATA_PATH = os.environ.get("RAW_DATA_PATH")

GCLOUD_PROJECT_ID = os.environ.get("GCLOUD_PROJECT_ID")
GCP_REGION = os.environ.get("GCP_REGION")

BUCKET_NAME = os.environ.get("BUCKET_NAME")
GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")

# ---------------- CONSTANTS ----------------
IMAGE_RESCALE_RATIO = 1. / 255

ROTATION_RANGE = 15
SHEAR_RANGE = 0.2
ZOOM_RANGE = 0.2
WIDTH_SHIFT_RANGE = 0.1
HEIGHT_SHIFT_RANGE = 0.1

IMAGE_TARGET_WIDTH = 100
IMAGE_TARGET_HEIGHT = 100

BOX_X1 = 0
BOX_X2 = 34
BOX_Y1 = 66
BOX_Y2 = 100

